### ISSUE TITLE
how do i integrate this project into laravel? Any help??

### ISSUE THREAD

**Issue by sath26** [tralves/vue-gdrive#1]

**Comment by tralves** [comment]
Hello!

That will depend on what type of integration you are trying to achieve. This project is 100% JavaScript, meaning that the browser connects directly to Google drive to open/store files and for the real-time collaboration stuff.

If you want to laravel to connect to gdrive, accessing the user's data, then this code will not be of much help.

Can you be more specific about what you are trying to achieve?

**Comment by sath26** [comment]
ok!!
I would integrate this javascript project. It provides all the features that I need. However, I wanted to know that there are so many folders of code, will I put them in resource/asset of laravel where other js code are put??

**Comment by tralves** [comment]
You have 2 options:

1. after you run `npm run build` copy the files in the `dist` to a separate folder under `public` and then create a route to that folder. This will not actually "integrate" the app in laravel. Laravel will just serve the app as if it was a static html page.

2. copy the .js, .css and .vue to wherever you have the other files of the same type. Then you will compile the app with the rest of your files with Laravel Mix (for Laravel 5.4) or Elixir (Laravel <=5.3).

Please note that this project was not designed to be something you could easily integrate with Laravel or whatever else. It just shows how you can integrate a Vue.js app with Google Drive.

So, first, you should make a Vue app with Laravel, then look into this project and use it's code as you see fit.

Sorry if I can't be more explicit, but that's because there is no easy way to simply drop this project in Laravel. You will have to know both Laravel and Vue to go somewhere.
