### ISSUE TITLE
Npm versions conflict

### ISSUE THREAD

**Issue by mustafat0k** [tralves/vue-gdrive#2]
Npm install command doesn't work anymore. Probably this about node version because of two years past.
Will you upgrade?  Otherwise, I need to do again from the beginning.

Output: https://gist.github.com/hacicavcav/4fcde2a4e914638ae899860b8e635788

**Comment by tralves** [comment]
Hey! Thank you for your interest in this project, but it is deprecated beyond repair. Google no longer supports these Google Drive APIs.

You may read the code, maybe it will help you somehow, but I would not start a new project from a 2yr old foundation.

**Comment by mustafat0k** [comment]
I thank you too for the return.  👍  I want to ask one question. Can you zip to files in node_modules?  If your desktop in has still. Maybe I can upgrade later.
It will save my time probably. I writed with pure php and laravel. I have two project but this better than of mine with material design already and browser-based. Because i don't need change to lot more things with this project. Maybe only reason is removed dependencies because doesn't install just a few things.
I tried yesterday all of them failed. 
I guess no problem with google drive api. Libraries deprecated or old versions not available now.
if not i should begin to write as quickly 
Note: I appreciate to you for the project is awesome :)

**Comment by tralves** [comment]
I don't have it installed on my computer anymore, sorry.

After giving a better look at the log, the error is in node-sass. Node SASS has lots of problems because it has to be compiled in your machine. Sending you a zip of my node_modules would not fix it. Try `npm i -g node-sass`.

Also, did you check the other project: https://github.com/tralves/collaborative-markdown-editor? Did it work?

Again, I would not use this project as a base for something new. The Material design lib is outdated, everything is outdated... Start a new project and use bits of code from this project.
